@param gg.jte.Content content

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciamento de Funcionários</title>
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>
    <header>
        CRUD de Funcionários
    </header>
    <main>
        ${content}
    </main>
    <footer>
        &copy; 2025 Sistema CRUD de Funcionários
    </footer>
</body>
</html>